### ISSUE TITLE
Error: foreign key constraint failed when running `cargo shuttle delete`

### ISSUE THREAD

**Issue by sd2k** [shuttle-hq/shuttle#561] opened 2023-01-02 08:55 UTC
I'm getting the following error when trying to run `cargo shuttle delete`:

```
❯ cargo shuttle delete
Error: 500 Internal Server Error
message: Persistence failure: Database error: error returned from database: (code: 787) FOREIGN KEY constraint failed
```

I haven't managed to successfully deploy anything yet (due to #527, I think?) so this might be an invalid command, but the error message could be nicer 🙂

**Comment by oddgrd** [comment] 2023-01-02 11:43
Hey Ben! Yeah, this one's not very kind on the eyes. We've known about this bug but must have forgotten to open an issue for it, so thanks for that! 

The delete op does actually work (in that it stops the running deployment), but I believe the root of this bug is that we ignore the error in `delete_deployments_by_service_id`. This means the `delete_service` handler will proceed with stopping the deployment despite getting a FK error. When we then try to delete the service we'll get the FK error again, and since we don't ignore it here a 500 error will be returned from the handler (but the service will have already stopped).

For reference, this is the deployer handler called by `cargo shuttle delete`: https://github.com/shuttle-hq/shuttle/blob/main/deployer/src/handlers/mod.rs#L253

**Comment by InfernapeXavier** [comment] 2023-01-29 06:16
Hey @oddgrd I ran into the same error today trying to stop my deployment. I can confirm that it definitely is still running despite me getting this error.

**Comment by oddgrd** [comment] 2023-02-06 09:32
Ah, thanks! Yes, it does seem there is an issue with stopping deployments as well. We've resolved this in a major refactor of our backend, but it may be a while until it gets merged. In other words, fixing the actual stoppage is out of scope for this issue.

An update on what we want to solve this bug (the FK error): we don't actually want to delete anything, rather we want to stop the service and change the state of the related tables to `Stopped`. We could also change the name of the cli-command (and associated functions) to stop rather than delete.

**Closed** 2023-02-09 15:03 UTC
Labels: bug
