### ISSUE TITLE
[Bug]: database is locked

### ISSUE THREAD

**Issue by auipga** [shuttle-hq/shuttle#1201] opened 2023-09-05 22:08 UTC
### What happened?

Regularly reading this error while changing nothing and just rerunning the deployment:

> error returned from database: (code: 5) database is locked

### Version

v0.24.0

### Which operating system(s) are you seeing the problem on?

In deployment

### Which CPU architectures are you seeing the problem on?

In deployment

### Relevant log output

```sh
cargo shuttle logs *****

 INFO Entering queued state
TRACE shuttle_deployer::deployment::queue: getting a build slot
TRACE {uri="http://gateway:8001/stats/load"} shuttle_deployer::deployment::gateway_client: calling gateway
DEBUG hyper::client::connect::http: connecting to 10.99.0.14:8001
DEBUG hyper::client::connect::http: connected to 10.99.0.14:8001
DEBUG hyper::client::pool: pooling idle connection for ("http", gateway:8001)
TRACE {response="Response { status: 200, version: HTTP/1.1, headers: {\"content-type\": \"application/json\", \"content-length\": \"38\", \"date\": \"Tue, 05 Sep 2023 21:59:58 GMT\"}, body: Body(Streaming) }"} shuttle_deployer::deployment::gateway_client: Load response

 INFO Entering building state
 INFO     Finished release [optimized] target(s) in 0.17s

 INFO Entering crashed state
ERROR {error="Build error: Database error: error returned from database: (code: 5) database is locked"} shuttle_deployer::deployment::queue: service build encountered an error
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by auipga** [comment] 2023-09-05 22:14
Same with v0.25.0

**Comment by auipga** [comment] 2023-09-07 13:26
`cargo deploy` I ran a single deployment until it crashed.
`cargo logs ...` I read the logs.
update the code
`cargo deploy` rerun the deployment.

Although waiting a minute or more between the deployments reduced the likelihood of the mentioned error it still occurred _sometimes_. (It drove me a little crazy because I changed things back and forth but getting inconsistent results)

I read #1067 back when I created this issue but I thought that a _crashed_ deployment is not _running_ anymore hence no concurrency. 

I'll try your suggestion to `cargo shuttle project restart` and let you know if it helps.

**Comment by oddgrd** [comment] 2023-09-08 08:51
Ah, okay, thanks for the info! It does seem like this error can occur when having an active deployment and one building too, which is unexpected. We're about to make a change in the coming week that will stop writing logs to the deployer sqlite database, this should alleviate this issue since logs are the majority of writes to the DB. In the slightly longer term we aim to completely remove this DB from deployers (the container your service runs in), and of course support interuptible builds as stated in #1067.

**Comment by jonaro00** [comment] 2023-11-22 10:03
Although this bug is more rare now, it can still happen.

**Comment by auipga** [comment] 2023-12-20 13:36
@elbaro 

1. hello-world != helo
2. Output: Run `cargo shuttle project start`
   You ran: `cargo shuttle project **re**start` + `--allow-dirty`, why?
3. `--allow-dirty` is for **deployment**.
    ```shell
    $ cargo shuttle deploy -h
    ...
    Options:
          --allow-dirty
              Allow deployment with uncommitted files [aliases: ad]
    ...
    ```
4. `cargo shuttle project restart` has no `--allow-dirty` option. It would make no sense to have this option for restart. Maybe I did't get the point, so please explain in more detail.
5. Your issue seems not to be linked to this specific issue, so please open a new issue for your situation.

**Comment by elbaro** [comment] 2023-12-20 21:36
Well the first `project start` gave `[Bug]: database is locked` and the second `project start` gave it's already running error. I ran `restart` to clear any corrupted state. The dashboard page doesn't indicate it's running and I couldn't access the deployed page even after a few restarts. I am providing a data point where the cloud state might be corrupted from this bug.

--allow-dirty is a different issue as you said and probably I mixed the concept of deploy and start at the moment.

**Comment by jonaro00** [comment] 2023-12-28 12:18
This bug has become a lot more common now and we have raised the priority to solve it.

**Comment by lazyfuhrer** [comment] 2024-01-02 22:35
```
2024-01-03T03:55:09.866+05:30 [Deployer]  INFO Starting service
2024-01-03T03:55:14.870+05:30 [Deployer]  INFO Entering Crashed state
2024-01-03T03:55:14.870+05:30 [Deployer]  INFO Cleaning up crashed deployment
2024-01-03T03:55:14.870+05:30 [Deployer] ERROR shuttle_deployer::deployment::run: {error="Run error: errored while setting the new deployer address: Database error: error returned from database: (code: 5) database is locked"} Service encountered an error and crashed
```
Any idea how can I fix this ?

**Comment by jonaro00** [comment] 2024-01-03 10:43
The solution is usually to restart the project and deploy again.

**Comment by jonaro00** [comment] 2024-01-23 09:40
Update: This bug has been hard to reproduce, but it looks to be less frequent now than in previous weeks. We are also working on a bigger change that should eliminate this bug once and for all (getting rid of the sqlite dbs in deployers).

**Comment by gnomeria** [comment] 2024-02-03 00:21
I just got realized I got this issue. Even after a `cargo shuttle project restart` it kept erroring out. :(
Now after the second project restart, the status has not changed from `This project is booting up, please refresh the page in a few seconds`

**Comment by jonaro00** [comment] 2024-02-14 15:11
We have continued investigating this, and we made some improvements in 0.39.0 that we hope help reduce the frequency of this bug.

**Comment by jonaro00** [comment] 2024-02-21 11:50
The probability of getting this error seems to be reduced since 0.39.0

**Comment by jonaro00** [comment] 2024-03-07 10:47
Improvements in recent releases has made this error very rare now. We are continuing work on getting rid of it completely.

**Comment by jonaro00** [comment] 2024-10-22 23:41
Closing due to being solved on the shuttle.dev platform.

**Closed by jonaro00** 2024-10-22 23:41 UTC
Labels: T-Bug, S-Investigation, S-Accepted
