### ISSUE TITLE
[Bug]: thread panic in `cargo_shuttle` while using `cargo shuttle run`

### ISSUE THREAD

**Issue by rhedgeco** [shuttle-hq/shuttle#1259] opened 2023-09-21 02:45 UTC
### What happened?

When executing cargo shuttle run the binary builds successfully, but the main thread then panics within the `cargo_shuttle` crate. I was running fine on the updated `v0.26.0` for a bit, but then this started happening every time out of nowhere.

### Version

v0.26.0

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }

Caused by:
    0: transport error
    1: http2 error: stream error received: stream no longer needed
    2: stream error received: stream no longer needed', /home/rhedgeco/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-shuttle-0.26.0/src/lib.rs:911:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1651:5
   3: cargo_shuttle::Shuttle::local_run::{{closure}}
   4: cargo_shuttle::Shuttle::run::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::runtime::Runtime::block_on
   7: cargo_shuttle::main
```

### Duplicate declaration

- [x] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment] 2023-09-21 14:51
I saw your help thread, this seems to have been caused by the port being occupied right? We should investigate if we can capture when this is the case in cargo-shuttle, and print a useful error message. The first step would be to reproduce, which should be as easy as starting something on the a port, and then trying to `cargo shuttle run` on the same port.

**Comment by jonaro00** [comment] 2023-09-21 17:50
Related to #950 #954

**Comment by BadgerBloke** [comment] 2023-09-22 04:28
Hi @oddgrd I would like to work on this, please assign this to me

**Comment by jonaro00** [comment] 2023-09-22 11:41
So, the root issue is that the runtime and it's grpc server can panic when trying to open ports. My suggestions is to suggest a different port if the chosen one is already taken. Kind of like this 
![image](https://github.com/shuttle-hq/shuttle/assets/54029719/84c1a8b5-8d2a-4282-9a21-f60ccfc9e85d)

But there are some more steps involved.

The way it works now:
- cargo-shuttle takes in port argument (default 8000)
- starts the runtime with proto crate's `runtime::start()` on this port minus 1 (default 7999)
- runtime takes this port (7999) and starts a grpc server (tonic)
- cargo-shuttle sends a grpc load request, then a grpc start request that tells runtime to start the service on the original port (8000)
- runtime starts on port received (8000)

The code is laid out to support spawning more than one shuttle-runtime at the same time. If there is more than one to spawn, their runtime port pairs would be (8001 with 7998), (8002 with 7997), etc.

So, when we check if we need to suggest a new base port, we actually need to check a port range, currently [base - N, base + N - 1], where N is the number of runtimes to start.
I suggest that the grpc server ports can be selected randomly with `pick_unused_port()` , just like the provisioner server currently does, so that we only need to check the port range [base, base + N - 1] that the actual user services are going to run on.

The solution steps are:
- Refactor port selection in cargo-shuttle's call to `runtime::start` to use a random unused port for the grpc server.
- Check that the chosen base port (default 8000) and the following N-1 ports are open. (This is usually just one port)
  - If available, use those ports/that port
  - Else, increase the base port by 10 and prompt the user if they want to use that instead. Code from the init command can be re-used (`dialoguer::Confirm`).
  - BONUS (optional): Investigate if the prompt can time out after 10 seconds, so that the `cargo shuttle run` command is not blocking for interactivity in an unexpected way.
- If any port binding still fails, a better panic message can be introduced.

Feel free to ask in anything is unclear.

**Comment by BadgerBloke** [comment] 2023-09-22 12:35
> ...
> The solution steps are:
> ...
> 
> Feel free to ask in anything is unclear.

Sure @jonaro00 I'll get back to you in case  any further clarification is required.Thanks for providing such helpful detailed info ❤️

**Closed** 2023-10-02 08:24 UTC
Labels: T-Bug, S-Accepted
