### ISSUE TITLE
[create-shuttle-app]: allow `rustc@>=1.65.0`

### ISSUE THREAD

**Issue by ShaunSHamilton** [shuttle-hq/shuttle#648] opened 2023-02-23 19:29 UTC
Considering Rust's backwards-compatibility, it would be preferential to not require version `1.65.0` exactly for [create-shuttle-app](https://www.npmjs.com/package/create-shuttle-app).

```bash
✔ create-shuttle-app requires Rust v1.65.0, do you wish to install it now?
```

I have version `1.66.0` which should satisfy all conditions, and would prefer not needing to have 2 versions installed.

**Comment by oddgrd** [comment] 2023-02-24 10:41
Hey Shaun! Yes, any version >= 1.65 should work, but unfortunately we have had some bugs caused by our FFI when when a project is compiled with a different compiler than the `cargo-shuttle` binary is compiled with, especially on mac and windows: https://github.com/shuttle-hq/shuttle/issues/617. To make this more straightforward and to try to spare users of the CLI from dealing with this, we opted with forcing 1.65 for this version, since that's the compiler the release binary is compiled with. When we bump the version we compile our binary with, we will also bump the node-cli version requirement.

We could change this to only warn about the version requirement, however, and allow the user to proceed with their installation of rust if they want to... That may be the better option here.

**Comment by ShaunSHamilton** [comment] 2023-02-24 11:08
@oddgrd Thank you for the context.
If there is an existing bug when using new versions of the compiler, then I would leave the requirement; _everyone_ ignores warnings.

If you already have another issue tracking the bug/fix, then this can be closed 🙂

**Comment by oddgrd** [comment] 2023-02-24 16:36
Haha, fair point. :smile: I'll leave this issue up for now, we have some similar ones but I reckon more people will have this question when using the node-cli. Thanks!

**Comment by oddgrd** [comment] 2023-03-22 12:18
`create-shuttle-app` now works with any version >= to the one shuttle uses (1.65 now, 1.68 from next week), so I'll close this. :partying_face:

**Closed by oddgrd** 2023-03-22 12:18 UTC
